### ISSUE TITLE
Try image fetches as AJAX

### ISSUE THREAD

**Issue by jfesler** [falling-sky/source#115]
Niall suggests fetching images as AJAX.  Look into whether we can do that or not.
My concern with trying to fetch those images as AJAX is that the browser will try executing the images as javascript.

**Comment by simbha** [comment]
:+1:

**Comment by jfesler** [comment]
Btw: This was actually discussed back and forth with Niall rather intensely.  Ultimately, after about 20 messages, he wrote:

  After some exploring, it now seems to me that the response to an
  image-load request cannot conveniently be used to confirm host
  reachability in the given context.

This wasn't so much a WONTFIX but more of a TECHNICALLYNOTPOSSIBLE :-)
