### ISSUE TITLE
old data in faq

### ISSUE THREAD

**Issue by krombel** [falling-sky/source#124]
In the faq-section there is a reference to data that should be outdated.
"At least check, May 2013, we still see 0.5% broken visiting test-ipv6.com."

How is it today? Equally?

I would appreciate to update this.

**Comment by jfesler** [comment]
This last 60 days, has been 0.31%.
http://test-ipv6.com/stats.html

Changing the faq text requires translators to translate (again).  Until the change is more material I will hold off doing so.
