### ISSUE TITLE
Team Cymru IP services are down

### ISSUE THREAD

**Issue by jfesler** [falling-sky/source#132]
I have disabled the ASN (ISP) lookups code for now.  

Need to periodically see if Team Cymru is back up; and re-enable.

If the outage is extended:
- [ ] Provide a hosted service 
- [ ] Build it into https://github.com/falling-sky/go-gslb
- [ ] Check if MaxMind free license is compatible
- [ ] Alternately, build a pipeline using route views data
- [ ] Modify mod_ip to use the new hosted service
- [ ] Nag all mirror sites to switch to the new hosted service
- [ ] Perhaps have a feature flag in falling-sky that enables the new service; otherwise stays disabled (to prevent user-facing slowdowns until admins update)

**Comment by grzchr15** [comment]
http://stackoverflow.com/questions/13110386/ip-to-asn-mapping-http://archive.routeviews.org/dnszones/ shows i nice way to get the asn via a dns query  . Zones are available via  http://archive.routeviews.org/dnszones/

**Comment by jfesler** [comment]
I had not realized someone published ipv4 dns zones.   However, that's ipv4 only.

Cymru did come back - I'm going to mark this as "wont fix" for now.  But may come back to it.
Coming back to it will be painful as it will mean trying to get the ~50 official mirrors to all update the Apache module.
