### ISSUE TITLE
Reactive (for mobile) version

### ISSUE THREAD

**Issue by jfesler** [falling-sky/source#135]
Today I was indirectly asked if I will make a mobile version of the web site.  So far, the demand for this has been pretty low.  This was the second request .. in 5 years.

I do make a point of making the most useful information on the first tab shown.  That is the summary page; and that shows the IPv4 address, IPv6 address, any warnings, and the score.  This is identical as for desktop; as many people just don't need or want to know the details beyond that. And we try to keep that first page as simple as we can for people not technically inclined in this field.

This feature will be costly for me to implement, due to the amount of vacation time from my day job I'd have to burn to work on this instead.  Not only will a lot of the current html have to be rewritten (without harming the user-facing text), it will need to be extensively QA'd under all common browsers that visit the site.  We still get old browsers visiting - browsers older than frameworks such as Bootstrap support.

This tracking issue is for people to speak up if this is something they feel strongly is needed.

**Comment by jfesler** [comment]
:eyes:    Simply "subscribe" to notifications on this thread to indicate some interest.
:pencil2:    Adding text to this thread, in the form of what needs to improve (and why moving to a reactive design can do that), would be much more convincing. :-)

**Comment by jfesler** [comment]
I ran a Facebook ad on this (with an admittedly small budget), targeting people who previously "liked" test-ipv6.com.  In the post I ask about the need/benefit of making changes for mobile.  The post reached 800 people.  

Summary: 5 people asked for larger fonts, but no real changes beyond that.

I may at some point do some work in a mobile/reactive version of the web page, but I don't expect to take vacation time off explicitly to do it.   It may take a year or even two. It may wait until I take a break between employers.  Or, it might get done sooner if there's enough value for me to burn vacation time.

Again, if people *do* have an opinion, please chime in.  Even subscribing to this thread will help me easier the value of this feature request.

**Comment by ibenrodriguez** [comment]
Hey @jfesler - I tested the site with latest model iphone and android phones and did not experience any UI issues.  What does this ticket suggest with a "reactive" mobile website function?  It seems to work okay now.

I tried both of these tabs from Android Nexus 6P with Chrome on AT&T (no IPv6 due to use of proxy) and iPhone 6s Plus on Verizon (IPv6 perfect).

- [http://test-ipv6.com/](http://test-ipv6.com/)
- [http://test-ipv6.com/mirrors.html](http://test-ipv6.com/mirrors.html)

Why not ask for volunteers to help contribute so you don't have to do it all?

**Comment by jfesler** [comment]
@ibenrodriguez, this stated as an ask by someone wanting me to move to a specific javascript framework, of which the major feature was to more easily build reactive sites.

Since this site only targets devices with full javascript capable browsers, this eliminates feature phones entirely; and pushes the minimum bar to smart phones only.

I personally have no problems with the site with an iPhone or with an Android mini tablet.  I actually use the phone pretty regularly as a device since that's what is always in my pocket.

As to being able to have volunteers: I'm not at all against it; but the build environment is super cumbersome.  This is a big part of why now mirrors just rsync the finished product via cron.  It isn't that I don't want the help; but more than I don't expect the help. :-)

I am reconsidering how the site builds from raw inputs to final product; at some point I may change the "compiler" from the mess of perl scripts to a single go binary.  If/when I do that, it might be more realistic for people to realistically contribute javascript changes.

That said, if someone who was a "real" developer had a better way to do things, I'd certainly be open to it.  The only real concern I'll have is not losing translations in the process, since roughly 80 people have contributed significant time to translating the site to 24 languages.

**Comment by jfesler** [comment]
Not enough interest. Closing.

If someone else wants to work on this, I'll help provide guidance.  The project is in better shape for builds than it was a few months ago.
