### ISSUE TITLE
Error in Wiki

### ISSUE THREAD

**Issue by theel0ja** [falling-sky/source#158]
https://github.com/falling-sky/source/wiki

"About the name: IPv6 has been around for the last decade; however, industry has mostly ignored it. IPv4 will never run out of IP space!"

IPv4? I think that should be IPv6..

**Comment by Dratone** [comment]
No - he's referencing the saying of the industry at the time. I.e. - they didn't implement IPv6 in the early days stating that "IPv4 will never run out of IP space"
