### ISSUE TITLE
I18n seems not automatically applied in some links in the website.

### ISSUE THREAD

**Issue by Geno1024** [falling-sky/source#160]
For example, when I selected another language in [./index.html](http://test-ipv6.com/index.html), it will href to, for example, [./index.html.zh_CN](http://test-ipv6.com/index.html.zh_CN). 
However, all other links, except any links mechanically adding a hash sign(#) after its URL, will jump to English version. For example, clicking the "常见问题" (FAQ) on [Simplified Chinese version of index.html](http://test-ipv6.com/index.html.zh_CN), will jump to [English version of faq.html](http://test-ipv6.com/faq.html), not [Simp. Chinese version of faq.html](http://test-ipv6.com/faq.html.zh_CN).
It seems something can be done better on this website :-)

**Comment by jfesler** [comment]
This hasn't been a big use case; most of the content gets rendered in-page.   However, I do understand it.  And agree that more can be done that what we have now.

Plan:
 - Function that generates FAQ links, should check if the current page overrides the browser language
 - If so, the rendered links should also override the browser language

I'm not sure how quickly I'll do this, as things are busy for me right now.  But I do agree it should get done.  Thank you for opening this issue.

**Comment by jfesler** [comment]
generated FAQ links were done some time ago.  This is more about the static "/faq.html" links (etc).  

On load, if not a crawler, all /.*.html links are now  dynamically rewritten to include locale.
