### ISSUE TITLE
Mirrors can not be tested from IPv6-only.

### ISSUE THREAD

**Issue by leifnel** [falling-sky/source#170]
When connecting to the IPv6-version from an IPv6-only pc, the site works, but the mirror page refuses to show the status of the other mirrors, because the IPv4 test fail.

This IPv4-test should be removed when accessed on the IPv6 or ds version of the site.

**Comment by ValZapod** [comment]
this is normal, no?? https://ipv6.test-ipv6.com/ only works correctly...

**Comment by ValZapod** [comment]
I cannot reproduce that on windows at least. https://ipv6.test-ipv6.com/ mirror pages work normal with IPV6 only. Dunno.

**Comment by jfesler** [comment]
I'd expect all the mirrors to show grey since the IPv4 control is failing.

Sorry, I just haven't had much time for updates here. :-(

**Comment by ValZapod** [comment]
But this is not logical at least for https://ipv6.test-ipv6.com/. For standard site that's okay.

**Comment by jfesler** [comment]
The "other sites" tab works as expected, as it checks the IP results before
running the test.

The "mirrors" tab does not have that luxury.  For me to disable the IPv4
control, it will be for everyone visiting by that hostname.

**Comment by jfesler** [comment]
Pushing out a change to allow http://ipv6.* sites to skip the IPv4 control check on the mirror page.  It may take an hour to get pushed to all sites globally.
