### ISSUE TITLE
Abandoned and alone

### ISSUE THREAD

**Issue by alexa-v2** [falling-sky/source#171]
This project seems abandoned

Is it?

**Comment by jfesler** [comment]
No.  I personally spend $700/month for hosting and hardware.   40 other mirror sites also run to help provide local instances in their respective countries and to their nearby neighbors.

As to development, only urgent stuff happens, as my time is limited.   Significant features basically require me to take vacation from my day job.   But, no, it's not abandoned.

PRs are welcome.
