### ISSUE TITLE
It appears that you use a tunnel mechanism for either IPv4 or IPv6.

### ISSUE THREAD

**Issue by ValZapod** [falling-sky/source#173]
@jfesler What is the algorithm behind it? And what does it mean **precisely**? I am almost sure that my AS https://bgp.he.net/net/2a00:1370::/32 is not doing some 💩 with MPLS/IPV4toV6/whatever. But I will admit that sometimes it prints it (for a month), sometimes not. I have native IPV6 and DNSv6 that IS prefered. AAAA is not first though... /Sigh

There is a DPI of our government though...

**Comment by jfesler** [comment]
When your IPv4 address is advertised by a different AS than your IPv6 address, that notice is printed.

**Comment by ValZapod** [comment]
Oh, but that has nothing to do with tunneling! It is just MTS ISP controls MGTS ISP (100% of stock) and so sometimes MGTS use IPv4 from MTS... It is not tunneling...

**Comment by jfesler** [comment]
If you own both AS send me email with both AS.

**Comment by ValZapod** [comment]
No, better let it be. Now I understand the problem ;) Maybe better print smth good like "AS of IPv4 AS is not the same as IPv6"
And it is not 2 ASN... It is AS25513 and crazy amount of that belongs to MTS. https://bgp.he.net/search?search%5Bsearch%5D=MTS&commit=Search
