### ISSUE TITLE
Since chrome 79 links are upgraded to https automatically (mixed https/http content)

### ISSUE THREAD

**Issue by ValZapod** [falling-sky/source#174]
https://[2001:470:1:18::119]:80/images-nc/bg.gif?&testdomain=test-ipv6.com&testname=test_ipv6_img"
will not obviosly work. Lol

You can try to get TLS certificate for IP address. But i think that hell, no, you will not get it like https://1.1.1.1

https://www.ghacks.net/2020/04/02/chrome-81-mixed-content-images-will-be-upgraded-or-blocked/

**Comment by jfesler** [comment]
When I visit test-ipv6.com with Chrome 81, no links are automatically upgraded to HTTPS.  If you want to share a screen shot or something that more clearly illustrates what you have, you're welcome to.

I do not have the means to get a TLS certificate for all the IPv4 and IPv6 addresses of test-IPv6.com, most of which are distributed to providers around the world.

For support issues I prefer email. My contact info is at the bottom of the test-IPv6.com web site.

**Comment by ValZapod** [comment]
I mean https://ipv6.test-ipv6.com of course, open debug page ;) I just say that http://[ipv6]:80 image will be upgraded to https://[ipv6]:80, yep.
