### ISSUE TITLE
mtu120d Installation - must: nfq_create_queue (value false)

### ISSUE THREAD

**Issue by YI--** [falling-sky/source#180]
root@server100:~# rsync -av fsky@rsync.test-ipv6.com:stable/mtu1280d .
receiving incremental file list
mtu1280d/
mtu1280d/.gitignore
mtu1280d/LICENSE
mtu1280d/Makefile
mtu1280d/README.md
mtu1280d/mtu1280d
mtu1280d/mtu1280d.c
mtu1280d/init.d/
mtu1280d/init.d/mtu1280d
mtu1280d/originals/
mtu1280d/originals/libnetfilter_queue-1.0.2.tar.bz2
mtu1280d/systemd/
mtu1280d/systemd/mtu1280d.service
mtu1280d/upstart/
mtu1280d/upstart/mtu1280d.conf

sent 246 bytes  received 411,300 bytes  91,454.67 bytes/sec
total size is 410,318  speedup is 1.00
root@server100:~# 
root@server100:~# cd mtu1280d
root@server100:~/mtu1280d# less README.md
/usr/share/modules/init/bash: line 36: /usr/bin/tclsh: No such file or directory
/usr/share/modules/init/bash: line 60: export: module: not a function
root@server100:~/mtu1280d# make mtu1280d
make: 'mtu1280d' is up to date.
root@server100:~/mtu1280d# sudo make install upstart
sudo /usr/bin/install -c mtu1280d /usr/sbin/
Checking to see if your system uses upstart
test -d /etc/init/
Makefile:27: recipe for target 'upstart' failed
make: *** [upstart] Error 1
root@server100:~/mtu1280d# sudo make install init.d
sudo /usr/bin/install -c mtu1280d /usr/sbin/
/usr/bin/install -c init.d/mtu1280d /etc/init.d/
test -x /usr/sbin/update-rc.d && update-rc.d mtu1280d defaults && update-rc.d mtu1280d enable || true
Reminder - start the daemon or reboot; then update your ip6tables.
See the README.md file.
root@server100:~/mtu1280d# sudo /etc/init.d/mtu1280d start
must: nfq_create_queue (value false)
root@server100:~/mtu1280d# 

-----------------------
root@server100:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by jfesler** [comment]
On that version of Ubuntu, `make systemd` would be appropriate.

**Comment by YI--** [comment]
thank you very much for your help!
