### ISSUE TITLE
test-ipv6.com does not have an AAAA record

### ISSUE THREAD

**Issue by maffe** [falling-sky/source#183]
test-ipv6.com [does not](https://dnschecker.org/#AAAA/test-ipv6.com) have an AAAA record. It would be nice to be able to reach the website on IPv6-only connections.

(Background: To avoid IPv4 address conflicts when using a VPN, I disabled the local IPv4 DHCP server so the clients only get IPv6 addresses, which are guaranteed to be unique. Now those machines cannot reach test-ipv6.com anymore when not connected to the VPN.)

**Comment by jfesler** [comment]
Covered by [the faq](http://test-ipv6.com/faq). If you're on a true IPv6 only connection, without even NAT64, then please feel free to use ds.test-IPv6.com  or IPv6.test-IPv6.com.

**Comment by maffe** [comment]
Thank you for the explanation. I found your website via a [search engine](https://duckduckgo.com/?t=ffab&q=ipv6+test&ia=web). Unfortunately reading the FAQ requires a working connection :-) But I can see why it’s reasonable to omit the AAAA record.

Maybe you could try to have the search engine display a reference to ds.test-ipv6.com in the excerpt on the result page? Possibly that particular search engine uses the `<meta name="description" …>`, but I’m not sure. Or maybe change the page title to something like `Test your IPv6. | test-ipv6.com | ds.test-ipv6.com | ipv6.test-ipv6.com`, that should be displayed by most search engines.

**Comment by genofire** [comment]
Hmm, that is stange.
Maybe it would be cooler if under `test-ipv6.com` is dualstack and it will create `ipv4.test-ipv6.com` for ipv4 only ...
