### ISSUE TITLE
Link to help page cannot be opened in a new tab

### ISSUE THREAD

**Issue by maffe** [falling-sky/source#184]
The rendered HTML on `broken.html` contains `<a href='#' onclick='return help_page("faq_6to4.html","6to4")'> 6to4</a>`. It’s not possible to open the referenced `faq_6to4.html` in a new tab/window with the usual methods (for example, clicking with the mouse wheel). The link should rather be: `<a href='faq_6to4.html' onclick='return help_page("faq_6to4.html","6to4")'>6to4</a>`. (I’d have submitted a pull request but I’m not familiar with the template language.)

**Comment by jfesler** [comment]
thank you. when I have a chance, I'll look into updating the link generator that is used. this may be a month or two as my work+personal life is .. busier than I'd like it to to be.

**Comment by jfesler** [comment]
Changes are pushed for faq links, and also [more info] links.
Changes can take 24 hours to roll out depending on the mirror.
