### ISSUE TITLE
Willing to improve the German translation

### ISSUE THREAD

**Issue by zhengliw** [falling-sky/source#193]
Hello to the dev(s)!

Let's get straight into the topic: I want to improve the quality of the German translation or create/improve the Chinese one. I would love to contribute to this awesome project!

Greetings

**Comment by jfesler** [comment]
Best way to do that is on https://crowdin.com/project/falling-sky . Roughly 100 suggestions were made in German in the last day, and the editor for German is reviewing those suggestions.

This weekend I'll look into why the periodic test pushes to i18n.test-IPv6.com aren't happening.

**Comment by jfesler** [comment]
Periodic pushes for i18n.test-IPv6.com fixed.
