### ISSUE TITLE
Some sites fail in test page but succeed otherwise

### ISSUE THREAD

**Issue by embermctillhawk** [falling-sky/source#198]
On the "Other IPv6 Sites" tab, there are 4 sites which are consistently returning as bad on the test page, but other test methods seem to work fine.

Manually visitng the url `https://ipv6-test-ipv6.eurobilltracker.com/img/1x1.gif?&testdomain=test-ipv6.com&testname=sites` succeeds.
Also, on windows, `ping -6 ipv6-test-ipv6.eurobilltracker.com` succeeds.

The four sites are;
- eurobilltracker.com
- www.limeconsultants.com
- vulndetect.org
- www.duiadns.net

All four exhibit this behavior of commandline pings succeeding and the images loading, but returning a "fail" on the webpage.

**Comment by jfesler** [comment]
I can confirm at least the vulndetect one. 
![Screen Shot 2022-08-04 at 7 33 14 AM](https://user-images.githubusercontent.com/2780575/182873610-1465cff8-628f-46a3-bdd9-a7f0d6eafe73.png)

**Comment by jfesler** [comment]
all are resolved or removed.
