### ISSUE TITLE
PHP scripts no longer working on PHP 8 due to removed function

### ISSUE THREAD

**Issue by jjackzhn** [falling-sky/source#203]
Error:
```
[Fri Nov 10 00:05:08.108745 2023] [php:error] [pid 87032] [client 2001:468:1f07:ffca:99b:d830:2204:cf2e:53447] PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /var/www/test-ipv6.23.scconf.org/common.php:26\nStack trace:\n#0 /var/www/test-ipv6.23.scconf.org/survey.php(3): require()\n#1 {main}\n  thrown in /var/www/test-ipv6.23.scconf.org/common.php on line 26, referer: https://test-ipv6.23.scconf.org/
```

https://github.com/falling-sky/source/blob/3194944a825db2eb2ced19e314d5292318249755/templates/php/common.php#L26

get_magic_quotes_gpc() has been deprecated and removed. See https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

**Comment by jfesler** [comment]
Thanks - I will put in a change that checks for the presence of get_magic_quotes_gpc before using it.
def66d2cc8d721de1bd5e11faa338d35a1d124eb
