### ISSUE TITLE
avoids_ipv6 on new mirror setup

### ISSUE THREAD

**Issue by agreppin** [falling-sky/source#209]
Hello,

I made an alternative setup with lighttpd + custom fcgi backend (WIP).
I'm using Vivaldi/Chrome to test it and the `avoids_ipv6` warning is always shown.
The test URL is https://test-ipv6.chilibi.ch/.

To solve this (just annoying) problem, I found a workaround, that is change `GIGO.slowcount_delay` to `100` in index.js (`GIGO.use_queue = 1` also does the job).
The test URL is https://test-ipv6.chilibi.ch/site/index.html.

The cause of the problem is maybe that lighttpd responds faster that Apache, not sure. I need some advice on how to solve this, please.

Note1: when I paste the URL https://ds.test-ipv6.chilibi.ch/ip/ in the same browser, it always shows `type: ipv6`.

Note2: another problem with lighttpd is that is replace any Content-Type `application/javascript` to `text/javascript`; I had to transform it back with some lua glue to fully pass your validator.

**Comment by jfesler** [comment]
The site is not compatible with http/2.  http/2 does connection coalescing.  that is counter to what this site needs to do.

please disable h2 to solve the problem.

**Comment by agreppin** [comment]
Thank you for your answer I disabled http/2.
Now, I have to polish somewhat my setup before submitting as a new mirror.
Thank you for test-ipv6.com !

**Comment by jfesler** [comment]
Please keep in mind occasionally the list of supported languages will vary.  Not as often as it used to, but it does vary.

There's a redirect I expect to see, that reports the version of the languages and redirects.
https://github.com/falling-sky/source/blob/master/templates/apache/dot.htaccess#L82

The online validator doesn't care as much about the git version, but does care greatly about the signature, and will mark a mirror as non-compliant.

I'd recommend monitoring this url with any monitor software you have and will pay attention to:

  https://validator.test-ipv6.com/check/test-IPv6.chilibi.ch

I'd check this every 5-15 minutes.

For officially listed mirrors, I will /also/ monitor, and send nagios alerts, based on polling every 5 minutes, with the first alert happening at 4 hours (to avoid any transient issues), and every 24 hours after that.


I will go ahead and close this issue.
